### ISSUE TITLE
dls-pmac-control crashes if values are invalid

### ISSUE THREAD

**Issue by Jimbomonkey** [Observatory-Sciences/dls-pmac-control#5]
bl02i-mo-step-09 is currently experiencing the problems reported in Jira ticket BC-1378 

If I open dls-pmac-control.py it instantly closes, with the following message on the console:

```
Traceback (most recent call last):
  File "/dls_sw/prod/python3/RHEL7-x86_64/dls_pmaccontrol/3.0.0b3/prefix/lib/python3.7/site-packages/dls_pmaccontrol/motor.py", line 812, in customEvent
    self.updateMotors()
  File "/dls_sw/prod/python3/RHEL7-x86_64/dls_pmaccontrol/3.0.0b3/prefix/lib/python3.7/site-packages/dls_pmaccontrol/motor.py", line 663, in updateMotors
    self.CSStatusScreen.updateFeed(int(round(float(value[0]))))
  File "/dls_sw/prod/python3/RHEL7-x86_64/dls_pmaccontrol/3.0.0b3/prefix/lib/python3.7/site-packages/dls_pmaccontrol/CSstatus.py", line 575, in updateFeed
    self.feedSpin.setValue(feed)
OverflowError: argument 1 overflowed: value must be in the range -2147483648 to 2147483647
```
It doesn't seem to like the feedrate reporting 0

However, if I open the 'old' version of dls-pmac-control.py, it doesn't crash

**Comment by rjwills28** [comment]
I have added a check for the overflow error here - this fix is available in the released v3.0.0.
