### ISSUE TITLE
Crash when connecting to pmac: macroIcAddresses[i] out of range

### ISSUE THREAD

**Issue by rjwills28** [Observatory-Sciences/dls-pmac-control#9]
The application crashed when trying to connect to a pmac:
```
Traceback (most recent call last):
  File "/dls_sw/prod/python3/RHEL7-x86_64/dls_pmaccontrol/3.0.0/prefix/lib/python3.7/site-packages/dls_pmaccontrol/motor.py", line 294, in remoteConnect
    self.table.setRowCount(self.pmac.getNumberOfAxes())
  File "/dls_sw/prod/python3/RHEL7-x86_64/dls_pmaccontrol/3.0.0/lightweight-venv/lib/python3.7/site-packages/dls_pmaclib/dls_pmacremote.py", line 315, in getNumberOfAxes
    self._numAxes = 8 + self._getNumberOfMacroStationAxes()
  File "/dls_sw/prod/python3/RHEL7-x86_64/dls_pmaccontrol/3.0.0/lightweight-venv/lib/python3.7/site-packages/dls_pmaclib/dls_pmacremote.py", line 307, in _getNumberOfMacroStationAxes
    if macroIcAddresses[i] != "$0":
IndexError: list index out of range
Aborted
```

The pmac possibly has the wrong setting, but we still do not want the application to crash.

**Comment by rjwills28** [comment]
The issue here was that 4 commands were being sent to the pmac to determine the macro IC addresses. The code expects a 4 element array to therefore be returned. However in this case the pmac was returning an error ('\x07ERR005') and hence the index went out of range of the list. 
I have fixed this by catching the case where the return array does not have a length of 4 and if so return 0 for the number of macro stations. See commit: https://github.com/Observatory-Sciences/dls-pmac-lib/commit/8a17350172aa28d0c218733fc7c47425204f6975
